### ISSUE TITLE
allow the user to provide a path to qgis_detect

### ISSUE THREAD

**Issue by jannes-m** [paleolimbot/qgisprocess#18]
I would advise to give the user the possibility to specify a path to the QGIS installation location in `qgis_detect()`. This is most certainly only necessary for Windows users. But over the years I have seen the most interesting QGIS installation locations during workshops, all of which are not covered by the three covered choices in `qgis_detect_windows()` @JanCaha.

See also `RQGIS3::set_env()` for automatically searching the C: drive for a QGIS installation.

**Comment by JanCaha** [comment]
That was my initial idea as well. But actually @paleolimbot provided good arguments to handle it otherwise. 

There is the option to set path using: `options('qgisprocess.path' = "C:/Program Files/QGIS 3.14/bin/qgis_process-qgis.bat")`. If this is set, then it is used to set up QGIS path prior to searching elsewhere.

**Comment by jannes-m** [comment]
Ah, thanks for clarifying, and good to know, I will put this information in the vignette
