### ISSUE TITLE
Passing flags to GRASS GIS algorithms

### ISSUE THREAD

**Issue by Nowosad** [paleolimbot/qgisprocess#91]
Hi @paleolimbot!
I've been trying to pass an `-m` flag to `"grass7:r.geomorphon"`. I tested several approaches without any success and was unable to find any solutions online. Is there a way to pass flags to GRASS GIS algorithms?

```r
library(qgisprocess)
# library(terra)
# dem = rast(system.file("raster/dem.tif", package = "spDataLarge"))
qgis_show_help("grass7:r.geomorphon")

dem_wetness = qgis_run_algorithm("grass7:r.geomorphon", 
                                 elevation = dem, "-m")

dem_wetness = qgis_run_algorithm("grass7:r.geomorphon", 
                                 elevation = dem, -m)

dem_wetness = qgis_run_algorithm("grass7:r.geomorphon", 
                                 elevation = dem, flags = "-m")
```

**Comment by JanCaha** [comment]
QGIS does some parameter handling for these GRASS arguments, so the passing is not as straightforward as one would like it to be.

This however seems to work.

```
dem_wetness = qgis_run_algorithm("grass7:r.geomorphon", 
                                 elevation = dem, `-m`="true")
```

You have to wrap the parameter name in backtics, because `-m` is not valid parameter name in R. With backtics you can use it and qgisprocess will translate it correctly.

I figure it out from QGIS "Copy as ..." functionality in latest QGIS version. 

The call obtained from QGIS looks like this:
```
qgis_process run grass7:r.geomorphon --distance_units=meters --area_units=m2 --ellipsoid=EPSG:7004 --elevation=some_data.tif --search=3 --skip=0 --flat=1 --dist=0 --forms=TEMPORARY_OUTPUT ---m=true ---e=false --GRASS_REGION_CELLSIZE_PARAMETER=0 --GRASS_RASTER_FORMAT_OPT= --GRASS_RASTER_FORMAT_META=
```

The JSON for arguments then looks like this:
```
{
  "area_units": "m2",
  "distance_units": "meters",
  "ellipsoid": "EPSG:7004",
  "inputs": {
    "-e": false,
    "-m": true,
    "GRASS_RASTER_FORMAT_META": "",
    "GRASS_RASTER_FORMAT_OPT": "",
    "GRASS_REGION_CELLSIZE_PARAMETER": 0.0,
    "GRASS_REGION_PARAMETER": null,
    "dist": 0.0,
    "elevation": "some_data.tif",
    "flat": 1.0,
    "forms": "TEMPORARY_OUTPUT",
    "search": 3,
    "skip": 0
  }
}
```

**Comment by Nowosad** [comment]
Great! Thank you a lot @JanCaha -- for the answer and the explanation.

**Comment by JanCaha** [comment]
@Nowosad this might be of interest to you. You can use the [qgis](https://github.com/JanCaha/r_package_qgis) package to get help for the the QGIS tool in RStudio and also slightly better handling of these GRASS flags.

In the code that generates **qgis** package I replaced the `-` in the flags with `.` so that they became "normal" arguments and they are then handled internally to the correct output. So this code works:
```
qgis::grass7_r_geomorphon(elevation = dem, .m = TRUE)
``` 
And I think that this is much more accessible, given that you can press "F1" in RStudio to get basically QGIS help. This also tells you about types of the variables (flags) etc.
